show databases;
CREATE DATABASE MINIMAL_API;
USE MINIMAL_API;
SHOW TABLES;
CREATE TABLE ALUNO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL
);
CREATE TABLE DISCIPLINA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME_DISCIPLINA VARCHAR(100) NOT NULL
);
CREATE TABLE MATRICULA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ALUNO INT NOT NULL,
    ID_DISCIPLINA INT NOT NULL,
    NOTA FLOAT,
    APROVADO BOOL,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID),
    FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA (ID)
);
CREATE TABLE CERTIFICADO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_MATRICULA INT,
    FOREIGN KEY (ID_MATRICULA) REFERENCES MATRICULA(ID)
);

SELECT * FROM ALUNO;
SELECT * FROM DISCIPLINA;
SELECT * FROM MATRICULA;
SELECT * FROM CERTIFICADO;

DELETE FROM CERTIFICADO
WHERE ID>0;

DELETE FROM MATRICULA
WHERE ID>0;

DELETE FROM DISCIPLINA
WHERE ID>0;

DELETE FROM ALUNO
WHERE ID>0;


ALTER TABLE MATRICULA
ADD COLUMN NOME_ALUNO VARCHAR(100) AFTER ID_ALUNO,
ADD COLUMN NOME_DISCIPLINA VARCHAR(100) AFTER ID_DISCIPLINA;

ALTER TABLE CERTIFICADO
ADD COLUMN NOME_ALUNO VARCHAR (100) AFTER ID_MATRICULA,
ADD COLUMN NOME_DISCIPLINA VARCHAR (100) AFTER NOME_ALUNO,
ADD COLUMN NOTA FLOAT AFTER NOME_DISCIPLINA;


